name: Requirements txt

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - 
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Freezing Requirements to requirements.txt
        run: |
          pip freeze > requirements.txt
          git add requirements.txt
          git commit -m "bot fix requirements.txt"
          git push

