name: Flatmates Scraper

on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 10 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      -
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
       
      - name: Run flatmates script
        run: pip install -r src/requirements.txt

      - name: Run flatmates script
        run: |
          make extract
          make load

      # Runs a set of commands using the runners shell
      - 
        name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull
          git add *
          git commit -m "weekly flatmates scrape" -a --allow-empty
      -
        name: GitHub Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
